import React, { type ReactNode } from 'react';
import { cookies } from 'next/headers';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/navigation/Navigation';
import { appRoutes } from '@/constant/routes';
import { Toaster } from 'react-hot-toast';
import { rose } from 'tailwindcss/colors';
import { TRPCReactProvider } from '@/trpc/react';
import { cn } from '@/lib/utils';

interface Props {
  children: ReactNode;
  modal: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang='en'>
      <body
        className={cn(
          inter.className,
          'touch-pan-y bg-gradient-to-b to-black from-gray-950'
        )}
      >
        <TRPCReactProvider cookies={cookies().toString()}>
          {modal}
          <Navigation routes={appRoutes}>
            <main className='mt-16 flex min-h-screen flex-col items-center p-10'>
              {children}
            </main>
          </Navigation>
          <Toaster
            position='bottom-center'
            toastOptions={{
              duration: 2500,
              style: {
                background: '#111',
                color: rose['500']
              },
              iconTheme: {
                primary: rose['500'],
                secondary: 'black'
              },
              error: {
                style: {
                  background: rose['950'],
                  color: 'white'
                },
                duration: 4000
              }
            }}
          />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
