import React, { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation/Navigation';
import clsx from 'clsx';
import { appRoutes } from '@/constant/routes';

interface Props {
  children: ReactNode;
  modal: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children, modal }: Props) {
  throw new Error("it's me mario");

  return (
    <html lang='en'>
      <body
        className={clsx(
          inter.className,
          'bg-gradient-to-b from-gray-950 touch-pan-y'
        )}
      >
        <Navigation routes={appRoutes}>
          <main className='mt-16 flex min-h-screen flex-col items-center p-10'>
            {children}
          </main>
        </Navigation>
        {modal}
      </body>
    </html>
  );
}
